### ISSUE TITLE
Bold 系列字体的字重设置有误

### ISSUE THREAD

**Issue by Yuiinars** [CMBill/lxgw-wenkai-web#6]
- https://cdn.jsdelivr.net/npm/@callmebill/lxgw-wenkai-web@latest/lxgwwenkai-bold/result.css
- https://cdn.jsdelivr.net/npm/@callmebill/lxgw-wenkai-web@latest/lxgwwenkaimono-bold/result.css

其中的 `font-weight` 都被错误地设置为 400，而根据 [相关约定](https://developer.mozilla.org/docs/Web/CSS/font-weight)，bold 字体的字重应被设置为 700，谢谢。

```css
/* <font-weight-absolute> numeric values [1,1000] */
font-weight: 100;
font-weight: 200;
font-weight: 300;
font-weight: 400; /* normal */
font-weight: 500;
font-weight: 600;
font-weight: 700; /* bold */
font-weight: 800;
font-weight: 900;
```

**Comment by CMBill** [comment]
感谢你的提醒，已经在 [v1.330.1](https://www.npmjs.com/package/@callmebill/lxgw-wenkai-web/v/1.330.1) 更改此问题。其他的几个字体稍后会修改。

**Comment by CMBill** [comment]
字体原作者将原 Bold 字重改为了 Medium（[v1.500](https://github.com/lxgw/LxgwWenKai/releases/tag/v1.500)），还需要修改才能修复。
